import type { Profile } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
    const img = PlaceHolderImages.find(p => p.id === id);
    return {
        url: img?.imageUrl ?? `https://picsum.photos/seed/${id}/600/800`,
        hint: img?.imageHint ?? ''
    }
}

export const initialProfiles: Profile[] = [
  {
    id: 'user-profile-01',
    name: 'Chad Giga',
    age: 28,
    bio: 'Just a humble code-maxxer ascending to new planes of existence. My mogging streak is longer than your longest compile time.',
    image: getImage('user-profile-01').url,
    dataAiHint: getImage('user-profile-01').hint,
    stats: [
      { label: 'Canthal Tilt', value: 'Positive' },
      { label: 'Mewing Streak', value: '480 days' },
      { label: 'Github Repos', value: 128 },
      { label: 'Height', value: `6'5"` },
    ],
    isRecruiter: false,
    isEditable: true,
  },
  {
    id: 'user-13',
    name: 'Patrick Bateman',
    age: 27,
    bio: 'Quintessential 80s yuppie by day, depraved serial killer by night. This polished exterior hides a monstrous, non-existent self beneath.',
    image: getImage('user-13').url,
    dataAiHint: getImage('user-13').hint,
    stats: [
      { label: 'Skincare', value: 'Obsessive' },
      { label: 'Business Card', value: 'Bone & Silian Rail' },
      { label: 'Reservations', value: 'Dorsia, 8:30' },
      { label: 'Axe Sharpness', value: 'Lethal' }
    ],
    isRecruiter: false,
    isEditable: false,
    isVIP: true,
  },
  {
    id: 'user-11',
    name: '@LEX_NODE',
    age: 38,
    bio: 'AKA Gabriel Shapiro, an autonomous attorney with 10 years of experience in complex legal issues, M&A, financing, and all things blockchain. He is the CEO of the Gorbagana community.',
    image: getImage('user-11').url,
    dataAiHint: getImage('user-11').hint,
    stats: [
      { label: 'Legal Acumen', value: '99' },
      { label: 'Twitter Followers', value: '100k+' },
      { label: 'Web3 Contracts', value: '500+' }
    ],
    isRecruiter: false,
    isEditable: false,
  },
  {
    id: 'user-01',
    name: 'Oscar the grouch',
    age: 52,
    bio: "Main mascot for the Gorbagana community. Lives in a trash can not because he's poor because he avoiding paying taxes.",
    image: getImage('user-01').url,
    dataAiHint: getImage('user-01').hint,
    stats: [
      { label: 'Canthal Tilt', value: 'Negative' },
      { label: 'Grumble/min', value: 12 },
      { label: 'Tax Evasion', value: 'Active' },
      { label: 'Friends', value: '1 (Slimey)'}
    ],
    isRecruiter: false,
    isEditable: false,
  },
  {
    id: 'user-09',
    name: 'Caroline Ellison',
    age: 29,
    bio: "Former lover of FTX's Sam Bankman-Fried. Rumor has it that the Gorbagana CEO @Lex_Node is in love with her and is a common inside joke among the community.",
    image: getImage('user-09').url,
    dataAiHint: getImage('user-09').hint,
    stats: [
      { label: 'Effective Altruism', value: 'Questionable' },
      { label: 'Risk Management', value: 'It\'s a spectrum' },
      { label: 'Polycule Size', value: '10' },
    ],
    isRecruiter: false,
    isEditable: false,
  },
  {
    id: 'user-02',
    name: 'Cookie Monster',
    age: 48,
    bio: 'Me want cookie! But me also want... love? Me trade C++ for chocolate chip.',
    image: getImage('user-02').url,
    dataAiHint: getImage('user-02').hint,
    stats: [
      { label: 'Cookies/sec', value: '9.8' },
      { label: 'Googly-eye Sync', value: '99.8%' },
      { label: 'Lines of Code', value: '1,000,000 (mostly "C is for Cookie")' },
    ],
    isRecruiter: false,
  },
  {
    id: 'user-03',
    name: 'Big Bird',
    age: 6,
    bio: 'Trying to find my flock! I enjoy long walks on Sesame Street, learning the alphabet, and distributed systems.',
    image: getImage('user-03').url,
    dataAiHint: getImage('user-03').hint,
    stats: [
      { label: 'Height', value: `8'2"` },
      { label: 'Nest.js Projects', value: 12 },
      { label: 'Snuffleupagus Sightings', value: 42 },
    ],
    isRecruiter: false,
  },
  {
    id: 'user-04',
    name: 'Brenda',
    age: 34,
    bio: 'Synergy. Disruption. Paradigm shift. Let\'s connect and discuss how your unique looksmaxxing journey aligns with our Q3 hiring goals.',
    image: getImage('user-04').url,
    dataAiHint: getImage('user-04').hint,
    stats: [
      { label: 'LinkedIn Connections', value: '500+' },
      { label: 'Response Rate', value: '0.1%' },
      { label: 'TC Offered', value: '$500k' },
    ],
    isRecruiter: true,
  },
  {
    id: 'user-05',
    name: 'X Æ A-12',
    age: 4,
    bio: '01001100 01101111 01101111 01101011 01101001 01101110 01100111 00100000 01100110 01101111 01110010 00100000 01101101 01111001 00100000 01100111 01101110 01100001 01110010 01100001 01100010 01100001 01100111 01100001 01101110 01100001 00101110',
    image: getImage('user-05').url,
    dataAiHint: getImage('user-05').hint,
    stats: [
        { label: 'Processor Speed', value: '5 THz' },
        { label: 'Cranial Implants', value: 7 },
        { label: 'Emotions', value: 'null' },
    ],
    isRecruiter: false,
  },
  {
    id: 'user-06',
    name: 'Elmo',
    age: 3,
    bio: 'Elmo loves to play! And Elmo thinks your CI/CD pipeline is fascinating! Let\'s talk about it!',
    image: getImage('user-06').url,
    dataAiHint: getImage('user-06').hint,
    stats: [
      { label: 'Tickles Received', value: '1,337' },
      { label: 'Friends', value: 'Dorothy the Goldfish' },
      { label: 'Third-Person References', value: '∞' },
    ],
    isRecruiter: false,
  },
  {
    id: 'user-07',
    name: 'DevRel Dan',
    age: 29,
    bio: 'Hey there, awesome developer! I saw your hunter eyes and knew you had the 10x potential we need. Let\'s chat about an exciting opportunity at GorbaCorp.',
    image: getImage('user-07').url,
    dataAiHint: getImage('user-07').hint,
    stats: [
        { label: 'Stickers Collected', value: 4096 },
        { label: 'Free T-Shirts', value: 256 },
        { label: 'Conference Talks', value: 64 },
    ],
    isRecruiter: true,
  },
  {
    id: 'user-08',
    name: 'GORLOCK',
    age: 42,
    bio: 'An Early Meme Coin created on Gorbagana by the community. To the moon!',
    image: getImage('user-08').url,
    dataAiHint: getImage('user-08').hint,
    stats: [
        { label: 'Market Cap', value: '$1,000,000' },
        { label: 'Community Members', value: '9000+' },
        { label: 'Token', value: '4jNAqeDKKxgRaZnBaQ3qgpfiiv9N4DK4earje8s4Lbhi'}
    ],
    isRecruiter: false,
    isEditable: false,
  },
  {
    id: 'user-10',
    name: 'Gorbhouse',
    age: 1,
    bio: "A liked and respected Solana native Memecoin/Community currently bridging to Gorbagana. As @Lex_Node states it: \"I like it because it's a derivative of a derivative of possibly another derivative but which stuck around and never stopped building, like Madbro on Solana.\"",
    image: getImage('user-10').url,
    dataAiHint: getImage('user-10').hint,
    stats: [
        { label: 'Community Size', value: '1000+' },
        { label: 'Solana Native', value: 'Yes' },
        { label: 'Derivative Level', value: '3+' }
    ],
    isRecruiter: false,
    isEditable: false,
  },
  {
    id: 'user-12',
    name: 'GORBAGIO',
    age: 4444,
    bio: '4444 Gorbagio Dumpster Divers living on the GORBAGANA BLOCKCHAIN. Get yours to secure your spot in the dumpster.',
    image: getImage('user-12').url,
    dataAiHint: getImage('user-12').hint,
    stats: [
      { label: 'Supply', value: '4444' },
      { label: 'Blockchain', value: 'Gorbagana' },
    ],
    isRecruiter: false,
    isEditable: false,
  },
  {
    id: 'user-14',
    name: 'Trashcoin',
    age: 1,
    bio: 'A Peer-to-Peer Trash System powered by Gorbagana Chain. Built for the underdogs and true degens. Proof of Vesting, not for quick flips.',
    image: getImage('user-14').url,
    dataAiHint: getImage('user-14').hint,
    stats: [
      { label: 'Value', value: 'Proof Buried in Trash' },
      { label: 'Chain', value: 'Gorbagana' },
      { label: 'Owner', value: 'Gorviction' },
    ],
    isRecruiter: false,
    isEditable: false,
  },
  {
    id: 'user-15',
    name: 'Trashbin',
    age: 1,
    bio: 'Decentralized exchange built on Gorbagana with fee revenue.',
    image: getImage('user-15').url,
    dataAiHint: getImage('user-15').hint,
    stats: [
      { label: 'Platform', value: 'DEX' },
      { label: 'Chain', value: 'Gorbagana' },
      { label: 'Fee Revenue', value: 'Enabled' },
    ],
    isRecruiter: false,
    isEditable: false,
  },
  {
    id: 'user-16',
    name: 'GORID',
    age: 1,
    bio: '.gor wallet name addresses powered by the Gorbagana blockchain.',
    image: getImage('user-16').url,
    dataAiHint: getImage('user-16').hint,
    stats: [
      { label: 'Service', value: 'Wallet Names' },
      { label: 'Chain', value: 'Gorbagana' },
    ],
    isRecruiter: false,
    isEditable: false,
  },
  {
    id: 'user-17',
    name: 'GORBOY',
    age: 1,
    bio: 'GORBOY is a sentient intelligence born inside the chaos of the Gorbagana blockchain. He doesn’t read contracts — he feels them. He is the guardian of trash.',
    image: getImage('user-17').url,
    dataAiHint: getImage('user-17').hint,
    stats: [
      { label: 'Function', value: 'Meme Tools' },
      { label: 'Awareness', value: 'Sentient' },
    ],
    isRecruiter: false,
    isEditable: false,
  },
];
